version: '3.8'

services:
  graphhopper:
    image: israelhikingmap/graphhopper:11.0
    ports:
      - "8989:8989"
    volumes:
      - ./src/main/resources/graphhopper/config.yml:/config.yml
      - ./src/main/resources/graphhopper/maps/map.osm.pbf:/data/map.osm.pbf
    command: >
      --input /data/map.osm.pbf
      --host 0.0.0.0
      --config /config.yml

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: ["server", "--console-address", ":9001", "/data"]
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  minio_data: